name: shopify-cli-example-app

up:
  - node:
      yarn: true
      version: v16.13.0
      packages:
        - ./
        - ./home
        - ./ui-extensions/checkout_post_purchase
        - ./scripts/payment_method
