name: Checkout post purchase

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ui-extensions/checkout_post_purchase/**
      - .github/workflows/checkout-post-purchase.yml

env:
  NODE_VERSION: "16.13.0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'ui-extensions/checkout_post_purchase/yarn.lock'
      - name: Install dependencies
        run: |
          yarn install --cwd ui-extensions/checkout_post_purchase
      - uses: shopify/shopify-cli-action@v1
        with:
          path: 'ui-extensions/checkout_post_purchase'
          command: 'extension build'
