name: Checkout post purchase deploy

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "16.13.0"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'ui-extensions/checkout_post_purchase/yarn.lock'
      - name: Install dependencies
        run: |
          yarn install --cwd ui-extensions/checkout_post_purchase
      - name: Deploy
        uses: shopify/shopify-cli-action@v1
        with:
          path: 'ui-extensions/checkout_post_purchase'
          auth-token: '${{ secrets.CLI_AUTH_TOKEN }}'
          command: 'extension push --api-key=${{ secrets.API_KEY }} --api-secret=${{ secrets.API_SECRET }} --extension-id=${{ secrets.EXTENSION_ID }} SHOPIFY_CLI_STACKTRACE=1'
