name: Home

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - home/**

env:
  NODE_VERSION: "16.13.0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'home/yarn.lock'
      - name: Install dependencies
        run: |
          yarn install --cwd home
      - name: Build
        working-directory: home
        run: yarn run build
