name: Home

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ui-extensions/checkout_post_purchase/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
