name: Payment method

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - scripts/payment_method/**

env:
  NODE_VERSION: "16.13.0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          yarn install --cwd scripts/payment_method
      - uses: shopify/shopify-cli-action@v1
        with:
          path: 'scripts/payment_method'
          command: 'script build'
