name: Checkout post purchase deploy

on:
  push:
    branches:
      - main
    paths:
      - scripts/payment_method/**

env:
  NODE_VERSION: "16.13.0"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'scripts/payment_method/yarn.lock'
      - name: Install dependencies
        run: |
          yarn install --cwd scripts/payment_method
      # - name: Deploy
      #   uses: shopify/shopify-cli-action@v1
      #   with:
      #     path: 'scripts/payment_method'
      #     auth-token: '${{ secrets.CLI_AUTH_TOKEN }}'
      #     command: 'extension push --api-key=${{ secrets.CLI_AUTH_TOKEN }} --api-secret=${{ secrets.API_SECRET }} --registration-id=${{ secrets.EXTENSION_ID }}'
